### ISSUE TITLE
OpenCV Problem

### ISSUE THREAD

**Issue by wassgha** [charlesmwang/facerec-server-node-sails#10]
Hello, I am trying to use this server in one my projects and I am having trouble running it. When I run npm install this happens : 

```
npm install opencv

opencv@0.4.0 preinstall /Users/wassgha/Downloads/facerec-server-node-sails-master/node_modules/.staging/opencv-49907bb6
node-gyp clean rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Requested 'opencv >= 2.3.1' but version of opencv is 2.x.x
gyp: Call to 'pkg-config --cflags "opencv >= 2.3.1"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/wassgha/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/Users/wassgha/.nvm/versions/node/v5.12.0/bin/node" "/Users/wassgha/.nvm/versions/node/v5.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean" "rebuild"
gyp ERR! cwd /Users/wassgha/Downloads/facerec-server-node-sails-master/node_modules/.staging/opencv-49907bb6
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN grunt-contrib-clean@0.4.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-coffee@0.7.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-concat@0.3.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-copy@0.4.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-cssmin@0.6.1 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-jst@0.5.0 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-less@0.5.2 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-uglify@0.2.2 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN grunt-contrib-watch@0.4.4 requires a peer of grunt@~0.4.0 but none was installed.
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/wassgha/.nvm/versions/node/v5.12.0/bin/node" "/Users/wassgha/.nvm/versions/node/v5.12.0/bin/npm" "install" "opencv"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! opencv@0.4.0 preinstall: `node-gyp clean rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@0.4.0 preinstall script 'node-gyp clean rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp clean rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wassgha/Downloads/facerec-server-node-sails-master/npm-debug.log
```

Any idea on how to fix it?

Thank you in advance.

**Comment by rupalipemare** [comment]
Even I'm getting the same issue . Tried installing several times

**Comment by wassgha** [comment]
@rupalipemare You can see my approach here https://github.com/wassgha/MirrorOS/tree/prosperi I combined Python and python-shell to get the same effect.
